development:
  adapter: postgresql
  encoding: utf8
  database: society_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: society_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: society_production
  pool: 5
  username:
  password:
